version: '2.27'

services:
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: